package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2017-12-21T11:35:25.774+08:00
 * Generated source version: 3.1.14
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "SMBBOMServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SMBBOMServiceSoap {

    @WebMethod(operationName = "GetSMBStandardPriceList", action = "http://tempuri.org/GetSMBStandardPriceList")
    @RequestWrapper(localName = "GetSMBStandardPriceList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSMBStandardPriceList")
    @ResponseWrapper(localName = "GetSMBStandardPriceListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSMBStandardPriceListResponse")
    @WebResult(name = "GetSMBStandardPriceListResult", targetNamespace = "http://tempuri.org/")
    public org.tempuri.SMBReturnModel getSMBStandardPriceList(
        @WebParam(name = "parameterList", targetNamespace = "http://tempuri.org/")
        org.tempuri.ArrayOfSMBParameterModel parameterList
    );
}
