package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2017-12-21T11:35:25.780+08:00
 * Generated source version: 3.1.14
 * 
 */
@WebServiceClient(name = "SMBBOMService", 
                  wsdlLocation = "file:/F:/Eclipse/Eclipse1/eclipse-jee-mars-R-win32-x86_64/workspace/SMBBOMService.WSDL",
                  targetNamespace = "http://tempuri.org/") 
public class SMBBOMService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "SMBBOMService");
    public final static QName SMBBOMServiceSoap = new QName("http://tempuri.org/", "SMBBOMServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/F:/Eclipse/Eclipse1/eclipse-jee-mars-R-win32-x86_64/workspace/SMBBOMService.WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SMBBOMService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/F:/Eclipse/Eclipse1/eclipse-jee-mars-R-win32-x86_64/workspace/SMBBOMService.WSDL");
        }
        WSDL_LOCATION = url;
    }

    public SMBBOMService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SMBBOMService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SMBBOMService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SMBBOMService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SMBBOMService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SMBBOMService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns SMBBOMServiceSoap
     */
    @WebEndpoint(name = "SMBBOMServiceSoap")
    public SMBBOMServiceSoap getSMBBOMServiceSoap() {
        return super.getPort(SMBBOMServiceSoap, SMBBOMServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SMBBOMServiceSoap
     */
    @WebEndpoint(name = "SMBBOMServiceSoap")
    public SMBBOMServiceSoap getSMBBOMServiceSoap(WebServiceFeature... features) {
        return super.getPort(SMBBOMServiceSoap, SMBBOMServiceSoap.class, features);
    }

}
