
package org.tempuri;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2017-12-21T11:35:25.778+08:00
 * Generated source version: 3.1.14
 * 
 */
 
public class SMBBOMServiceSoap_SMBBOMServiceSoap_Server{

    protected SMBBOMServiceSoap_SMBBOMServiceSoap_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SMBBOMServiceSoapImpl();
        String address = "http://10.96.39.118:8083/SMBBOMService.asmx";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SMBBOMServiceSoap_SMBBOMServiceSoap_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
