spring:
  datasource:
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://127.0.0.1/test?characterEncoding=utf-8&useSSL=false
    secondary:
      driver-class-name: com.mysql.jdbc.Driver     
      username: root
      password: root 
      url: jdbc:mysql://127.0.0.1/world?characterEncoding=utf-8&useSSL=false 
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        maximumPoolSize: 30
        minimumIdle: 5
        autoCommit: true
        useLocalSessionState: true
        useLocalTransactionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        connectionTestQuery: SELECT 1
  jpa:
      show-sql: true
      hibernate:
        naming:
        #方言  
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8      
  
  
#  jpa:
#    show-sql: true

server:
  port: 9090




